/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#2d3449",
        "surface-tint": "#b4c5ff",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#131b2e",
        "tertiary-fixed": "#f0dbff",
        "tertiary-container": "#943fe2",
        "on-tertiary": "#490080",
        "on-background": "#dae2fd",
        secondary: "#4cd7f6",
        "surface-container-high": "#222a3d",
        "on-surface-variant": "#c3c6d7",
        "primary-fixed": "#dbe1ff",
        "surface-dim": "#0b1326",
        surface: "#0b1326",
        "on-secondary-container": "#00424e",
        "tertiary-fixed-dim": "#ddb7ff",
        "on-tertiary-fixed-variant": "#6900b3",
        "on-primary-fixed": "#00174b",
        tertiary: "#ddb7ff",
        "inverse-surface": "#dae2fd",
        "on-tertiary-fixed": "#2c0051",
        primary: "#b4c5ff",
        "primary-fixed-dim": "#b4c5ff",
        "secondary-fixed": "#acedff",
        "on-primary": "#002a78",
        "inverse-on-surface": "#283044",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-fixed-dim": "#4cd7f6",
        "surface-container-highest": "#2d3449",
        "surface-container": "#171f33",
        "surface-container-lowest": "#060e20",
        "error-container": "#93000a",
        "inverse-primary": "#0053db",
        "on-surface": "#dae2fd",
        "secondary-container": "#03b5d3",
        "surface-bright": "#31394d",
        "on-tertiary-container": "#faecff",
        "on-secondary-fixed-variant": "#004e5c",
        "on-primary-container": "#eeefff",
        background: "#0b1326",
        "on-secondary": "#003640",
        outline: "#8d90a0",
        "outline-variant": "#434655",
        error: "#ffb4ab",
        "on-secondary-fixed": "#001f26",
        "on-error": "#690005",
        "primary-container": "#2563eb",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        unit: "8px",
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
}